#!/bin/sh

notmuch new

notmuch tag +openbsd -inbox -- to:"/openbsd\.org/"
notmuch tag +gnu -inbox -- to:"/gnu\.org/"
notmuch tag +9front -inbox -- to:"/9front\.org/"
notmuch tag +9front -inbox -- to:"/cat-v\.org/"
notmuch tag +system -inbox -- from:"/enzu\.ru/"
notmuch tag +misc -inbox -- tag:inbox

notmuch tag -gnu +gnu-commits -- to:emacs-diffs@gnu.org
notmuch tag -gnu +gnu-commits -- to:guix-commits@gnu.org
notmuch tag -9front +9front-commits -- to:9front-fqa@9front.org
notmuch tag -9front +9front-commits -- to:9front-commits@9front.org
notmuch tag -openbsd +openbsd-commits -- to:source-changes@cvs.openbsd.org
notmuch tag -openbsd +openbsd-commits -- to:ports-changes@cvs.openbsd.org

notmuch tag -gnu +gnu-bugs -- from:"/debbugs.gnu.org/" or to:"/debbugs.gnu.org/"
notmuch tag -openbsd +openbsd-bugs -- from:bugs@openbsd.org or to:bugs@openbsd.org
